version: '0.2'
ignorePaths:
  - pnpm-lock.yaml
  - '*.tsbuildinfo'
dictionaryDefinitions:
  - name: custom-dictionary
    path: ./.cspell/custom-dictionary.txt
    addWords: true
dictionaries:
  - custom-dictionary
words: []
ignoreWords: []
import: []
